import path from "node:path";

import type { Article } from "./articles.js";

const usageGuideAssetBase = "/library-assets/managed/articles/usage-guide";

function usageGuideImage(fileName: string, alt: string, size: "medium" | "large" | "full" = "large") {
  return `![${alt}](${usageGuideAssetBase}/${fileName}){size=${size}}`;
}

export function getDefaultLibraryDocumentationSourceDir(repoRoot: string) {
  return path.join(path.resolve(repoRoot), "materials", "default-library", "usage-guide");
}

export function getDefaultLibraryDocumentationAssetDirSegments() {
  return ["articles", "usage-guide"] as const;
}

export function getDefaultLibraryDocumentationAssetFileNames() {
  return [
    "launcher-home.png",
    "owner-overview.png",
    "owner-work-form.png",
    "owner-recording-form-top.png",
    "owner-recording-links-guide.png",
    "owner-auto-check.png",
    "owner-review.png",
    "owner-batch-update.png",
    "owner-articles.png",
    "retrieval-home.png",
  ];
}

function buildDefaultUsageGuideMarkdown() {
  return [
    "# 不全书使用手册",
    "",
    "这份手册面向安装版用户。默认资料库是一个空库，只附带本篇专栏和相关图片，方便你在本地从零开始维护自己的作曲家、人物、团体、作品、版本与专栏内容。",
    "",
    "## 1. 启动器与三个入口",
    "",
    usageGuideImage("launcher-home.png", "启动器首页"),
    "",
    "- **打开本地构建库**：打开当前资料库已经构建好的站点，适合浏览与检查前台展示效果。",
    "- **打开维护工具**：进入日常维护界面，用于创建条目、编辑字段、运行检查、构建站点和导出资料库。",
    "- **打开版本检索工具**：用于辅助版本条目的检索和候选整理，通常配合维护工具使用。",
    "",
    "> 建议的日常工作路径是：先在维护工具里录入和检查内容，再点击“构建不全书”，最后用“打开本地构建库”检查站点效果。",
    "",
    "## 2. 维护工具总览",
    "",
    usageGuideImage("owner-overview.png", "维护工具总览"),
    "",
    "- 顶部操作区负责导入库、导出库、构建站点、打开站点和刷新数据。",
    "- 左侧是数据概览与问题提示，用于快速了解资料库规模和待处理事项。",
    "- 中间和右侧是当前标签页的工作区与表单区，用于搜索、编辑、检查、批量处理和专栏维护。",
    "- 对条目做了修改后，需要显式点击保存，内容才会真正写入资料库。",
    "",
    "## 3. 资料库、导入导出与构建",
    "",
    "### 3.1 默认资料库",
    "",
    "- 安装版自带一个默认资料库，位于安装目录里的 `library` 文件夹。",
    "- 默认资料库是空模板，只包含库结构和《不全书使用手册》专栏，不包含任何测试条目或开发者个人资料。",
    "",
    "### 3.2 导入与导出",
    "",
    "- **导入库**：把另一台设备上的资料库复制过来后，在维护工具中导入即可继续使用。",
    "- **导出库**：把当前资料库完整导出到指定目录，便于备份、迁移和在其他设备继续维护。",
    "",
    "### 3.3 构建站点",
    "",
    "- 点击**构建不全书**后，当前资料库会生成一份完整静态站点，输出到资料库目录中的 `build/site`。",
    "- 构建完成后，可以直接用“打开本地构建库”检查实际展示效果。",
    "",
    "## 4. 创建基础条目",
    "",
    "### 4.1 作曲家、人物、团体、作品",
    "",
    usageGuideImage("owner-work-form.png", "基础条目编辑界面"),
    "",
    "- 这些条目是资料库的骨架，也是后续录入版本条目的前提。",
    "- 常见字段包括中文名、外文名、国家、摘要、导览文字、图片和关联专栏。",
    "- `slug`、排序键和作品类型路径这类内部字段会自动生成或自动维护，不需要手动输入。",
    "- 人物可以拥有复合身份，例如同一条目同时勾选“作曲家”和“指挥”。",
    "- 团体与人物是独立条目，不应互相覆盖；如果切换顶层标签，系统会自动清空不兼容表单，避免串值。",
    "",
    "## 5. 创建版本条目",
    "",
    usageGuideImage("owner-recording-form-top.png", "版本条目上半部分"),
    "",
    "- 版本条目对应具体录音或录像，需要挂在某个已经存在的作品条目下。",
    "- 版本条目通常会包含演出时间、地点、专辑名、发行商、图片、资源链接和参与者 `credits`（署名信息）。",
    "- 建议先准备好作曲家、作品，以及相关的人物或团体条目，再创建版本。",
    "",
    usageGuideImage("owner-recording-links-guide.png", "版本条目的导览与链接区域"),
    "",
    "- **导览文本**适合填写推荐理由、辨识提示和收听建议。",
    "- **关联专栏**适合补充长文说明。",
    "- **资源链接**既支持外部链接，也支持桌面版专用的本地资源链接。",
    "- 本地资源链接会出现在站点前台资源区，但通常只在当前设备有效；资料库导出到其他设备后，这类链接一般需要重新整理。",
    "",
    "## 6. 自动检查与候选审查",
    "",
    usageGuideImage("owner-auto-check.png", "自动检查界面"),
    "",
    "- 自动检查会根据当前条目类型给出候选补全结果，但不会直接覆盖正式数据。",
    "- 对人物、团体、作品等基础条目，自动检查更适合补齐摘要、国家、图片和命名规范。",
    "- 对版本条目，自动检查通常会联动版本检索工具，帮助整理候选链接和元信息。",
    "",
    usageGuideImage("owner-review.png", "候选审查界面"),
    "",
    "- 候选审查用于逐项确认或放弃自动检查结果。",
    "- 只有在这里确认应用后，候选内容才会写入正式资料库。",
    "",
    "## 7. 批量更新",
    "",
    usageGuideImage("owner-batch-update.png", "批量更新界面"),
    "",
    "- 批量更新适合一次处理多条版本草稿或待补录的版本。",
    "- 使用前建议先准备好作曲家、作品以及相关的人物和团体条目。",
    "- 建议先小范围测试你的输入格式，确认匹配逻辑正常后再扩大处理范围。",
    "",
    "## 8. 专栏",
    "",
    usageGuideImage("owner-articles.png", "专栏编辑界面"),
    "",
    "- 专栏用于承载不适合作为单一条目附属说明的长文本，例如使用手册、入门专题、人物合集和榜单。",
    "- 专栏支持 `Markdown`（标记语言）正文和图片插入，`slug` 会根据标题自动生成并维护。",
    "- 勾选“在首页展示”后，专栏会出现在站点首页的推荐专栏区域。",
    "",
    "## 9. 版本检索工具",
    "",
    usageGuideImage("retrieval-home.png", "版本检索工具"),
    "",
    "- 版本检索工具是维护工具的辅助组件，主要用于帮助版本条目生成候选结果。",
    "- 如果维护工具中的版本自动检查结果异常，可以单独打开它查看输入、候选和返回结果，便于排查问题。",
    "",
    "## 10. 推荐工作顺序",
    "",
    "1. 从默认空库开始，或导入已有资料库。",
    "2. 先创建作曲家、人物、团体和作品等基础条目。",
    "3. 再创建版本条目，补充导览文本、图片和资源链接。",
    "4. 运行自动检查，并在候选审查中确认需要应用的内容。",
    "5. 需要时使用批量更新处理多条版本。",
    "6. 编写专栏，并把适合公开展示的专栏勾选到首页。",
    "7. 点击“构建不全书”，再用“打开本地构建库”检查前台效果。",
    "8. 定期导出整个资料库，作为备份和迁移副本。",
    "",
    "## 11. 范围与限制",
    "",
    "- 自动检查和版本检索属于辅助功能，结果仍需要人工确认。",
    "- 本地资源链接适合桌面版个人使用，不适合直接公开到互联网。",
    "- 合并、批量更新和候选审查都建议先在小范围内试运行，再扩大到全库。",
    "- 构建后的站点是静态展示层，不会替代资料库本身；真正可编辑的数据仍保存在资料库目录中。",
  ].join("\n");
}

export function createDefaultLibraryArticles(now = new Date().toISOString()): Article[] {
  return [
    {
      id: "default-usage-guide",
      slug: "usage-guide",
      title: "不全书使用手册",
      summary: "面向安装版用户的完整上手说明，涵盖默认库、维护工具、自动检查、批量更新、专栏和构建流程。",
      markdown: buildDefaultUsageGuideMarkdown(),
      showOnHome: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}
